---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
#
# Additional ~/.fog config file with AWS EC2 credentials
# required.
#
# see: https://github.com/puppetlabs/beaker/blob/master/docs/how_to/hypervisors/ec2.md
#
HOSTS:
  centos-7:
    roles:
      - master
    platform: centos-7-x86-64-west
    hypervisor: ec2
    # refers to image_tempaltes.yaml AMI[vmname] entry:
    vmname: centos-7-ap-southeast-2
    # refers to image_tempaltes.yaml entry inside AMI[vmname][:image]:
    snapshot: aio
    # t2.micro is free tier eligible (https://aws.amazon.com/en/free/):
    amisize: t2.micro
    # required so that beaker sanitizes sshd_config and root authorized_keys:
    user: centos
CONFIG:
  type: aio
  :ec2_yaml: spec/acceptance/nodesets/ec2/image_templates.yaml
...
# vim: syntax=yaml
